import * as React from 'react';
import Head from 'next/head';
import type { AppProps } from 'next/app';
import { ChakraProvider } from '@chakra-ui/react';
import Layout from '@/components/Layout';
import { PokemonProvider } from '@/context/PokemonContext';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <PokemonProvider>
      <ChakraProvider>
        <Layout>
          <Head>
            <title>Pokemon Challenge</title>
            <meta name='description' content='Generated by create next app' />
            <meta
              name='viewport'
              content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/pokeball.svg' />
          </Head>
          <Component {...pageProps} />
        </Layout>
      </ChakraProvider>
    </PokemonProvider>
  );
}
